#server
server:
  port: 80
  tomcat:
    max-threads: 1000
  servlet:
    context-path: /
    #spring datasource
spring:
  datasource:
    url: jdbc:mysql:///hisystem?serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  aop:
    proxy-target-class: false
  mail: #邮件发送配置
    host: smtp.qq.com
    username: 3230335956@qq.com
    password: yjxqiadbitqscgjj
    default-encoding: UTF-8
    
    
    
#Spring mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/sys/*.xml

logging:
  level:
    com.cy: DEBUG
    
#page
pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count=countSql